EPA_Admin/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^upload/', 'epa.views.upload_data'),
    url(r'^send_url/', 'epa.views.upload_from_url'),    
    url(r'^delete/', 'epa.views.delete_data'),
    url(r'^prediction_data/$', 'epa.views.view_prediction_data'),
    url(r'^prediction_data/(?P<page>\d+)/(?P<page_size>\d+)/$', 'epa.views.view_prediction_data'),

    url(r'^account/my/$', 'epa.views.edit_user'),
    url(r'^account/change/$', 'epa.views.edit_user'),
    url(r'^account_delete/$', 'epa.views.delete_user'),
    url(r'^account/add/$', 'epa.views.add_user'),
    url(r'^account/register/$', 'epa.views.register'),
    url(r'^account/$', 'epa.views.view_user'),
    url(r'^login/$', 'epa.views.view_login'),
    url(r'^search_help/$', 'epa.views.search_help'),
    url(r'^help/$', 'epa.views.view_help'),
    url(r'^help/(?P<id>\d+)/$', 'epa.views.view_help'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login'),
    url(r'^reset/$', 'epa.views.reset_password'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'epa.views.view_prediction_data')

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

epa/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.core.files.storage import FileSystemStorage
from django.core.files import File
from EPA_Admin.settings import EPA_SHARED_FOLDER_DATA, EPA_SHARED_FOLDER, EPA_UPLOAD_DATA_FOLDER, MEDIA_ROOT, \
    EPA_UPLOAD_DATA_FILE_NAME_LENGTH, EPA_UPLOAD_DATA_THUMB_FOLDER, EPA_DEFAULT_THUMB_TXT_PATH, \
    EPA_DEFAULT_THUMB_IMAGE_PATH, EPA_THUMB_SIZE, EPA_HELP_CAT_LENGTH, EPA_HELP_TOPIC_LENGTH, \
    EPA_PREDICTION_FOLDER, EPA_PREDICTION_TITLE_LENGTH, EPA_EXECUTE_LENGTH
import datetime
import os
import string
import logging
import Image

logger = logging.getLogger(__name__)


class OverwriteStorage(FileSystemStorage):
    """
    Custum Storage. Django default storage never delete updated/deleted files.
    This storage is to make sure that all uploaded file is same file(and filename)
    with the original file
    """

    def _save(self, name, content):
        """
        Override the _save method
        """
        if self.exists(name):
            self.delete(name)
        return super(OverwriteStorage, self)._save(name, content)

    def get_available_name(self, name):
        return name


class UploadData(models.Model):
    FILE_TYPE = ((0, 'Image'), (1, 'Text'))
    file = models.FileField(upload_to=EPA_UPLOAD_DATA_FOLDER, storage=OverwriteStorage())
    thumbnail = models.ImageField(upload_to=EPA_UPLOAD_DATA_THUMB_FOLDER, blank=True, null=True)
    file_name = models.CharField(max_length=EPA_UPLOAD_DATA_FILE_NAME_LENGTH)
    user = models.ForeignKey(User, blank=True, null=True)
    date = models.DateTimeField(default=datetime.datetime.now())
    type = models.IntegerField(choices=FILE_TYPE)

    def __unicode__(self):
        return self.file_name

    def save(self, *args, **kwargs):
        """
        Custom save method.

        This will override the default save() to generate other field i.e thumbnail
        """
        super(UploadData, self).save(*args, **kwargs)
        try:
            thumb_name = ''
            thumb_path = ''
            if self.type == 0:
                thumb = Image.open(self.file.path)
                thumb.thumbnail(EPA_THUMB_SIZE, Image.ANTIALIAS)
                list_thumb_name = self.file_name.split('.')
                list_thumb_name.pop()
                thumb_name = string.join(list_thumb_name, '')
                thumb_path = MEDIA_ROOT + '/' + EPA_UPLOAD_DATA_THUMB_FOLDER + thumb_name + '_thumb.jpg'
                thumb.save(thumb_path, 'JPEG')

            else:
                thumb_name = 'default_text'
                thumb_path = EPA_DEFAULT_THUMB_TXT_PATH
            new_thumb = File(open(thumb_path, 'r'))
            self.thumbnail.save(thumb_name + '_thumb.jpg', new_thumb, save=False)
            super(UploadData, self).save(*args, **kwargs)
        except:
            if self.type == 0:
                thumb_name = 'default_image'
                thumb_path = EPA_DEFAULT_THUMB_IMAGE_PATH
            else:
                thumb_name = 'default_text'
                thumb_path = EPA_DEFAULT_THUMB_TXT_PATH
            new_thumb = File(open(thumb_path, 'r'))
            self.thumbnail.save(thumb_name + '_thumb.jpg', new_thumb, save=False)
            super(UploadData, self).save(*args, **kwargs)
            logger.error('UploadData.save(): failed to create thumbnail')


@receiver(models.signals.pre_delete, sender=UploadData)
def delete_signal(sender, instance, **kwargs):
    """
    Permanently delete file on fs on delete operation
    """
    if instance.file:
        try:
            #os.remove(EPA_SHARED_FOLDER + '/' + instance.file.name)
            os.remove(instance.file.path)
            _fname = instance.thumbnail.path.split('/')
            fname = _fname[len(_fname) - 1]
            if not fname[:7] == 'default':
                os.remove(instance.thumbnail.path)
        except:
            logger.error('UploadData.delete(): failed to delete file from shared folder')
            #raise OperationalError


class HelpCategory(models.Model):
    name = models.CharField(max_length=EPA_HELP_CAT_LENGTH)

    def __unicode__(self):
        return self.name


class HelpTopic(models.Model):
    title = models.CharField(max_length=EPA_HELP_TOPIC_LENGTH)
    content = models.TextField()
    category = models.ForeignKey(HelpCategory)

    def __unicode__(self):
        return self.title

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>EPA Administration</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet" href="/static/css/normalize.css">
        <link rel="stylesheet" href="/static/css/main.css">
        <link rel="stylesheet" href="/static/css/epa.css">
                <link rel="stylesheet" href="/static/css/jquery.fileupload.css">
        <link rel="stylesheet" href="/static/css/jquery.fileupload-ui.css">
        <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/static/js/excanvas.min.js"></script><![endif]-->
        <script src="/static/js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div id="mainContainer">
            <div id="header">
                {% block nav %}{% endblock  %}
            </div>
            {% block menu %}{% endblock menu %}
            {% block content %}{% endblock content %}
            <div id="footer">
                <div id="content">
                    <div id="copyright">&copy; 2014 All right reserved</div>

                </div>
            </div>
        </div>
        {% block popup %}{% endblock %}
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="/static/js/jquery.cookie.js"></script>
        <script src="/static/js/vendor/jquery.ui.widget.js"></script>

        <script src="/static/js/jquery.iframe-transport.js"></script>
        <!-- The basic File Upload plugin -->
        <script src="/static/js/jquery.fileupload.js"></script>
        <!-- The File Upload processing plugin -->
        <script src="/static/js/jquery.fileupload-process.js"></script>
        <!-- The File Upload user interface plugin -->
        <script src="/static/js/jquery.fileupload-ui.js"></script>
        <script src="/static/js/jquery.flot.min.js"></script>
        <script src="/static/js/jquery.flot.time.min.js"></script>
        <script src="/static/js/main.js"></script>

    </body>
</html>

templates/base_auth.html
{% extends "base.html" %}
{% block nav %}
    <div id="nav">
    <ul>
        <li>Hello {{ user.username }}</li>
        {% if user.is_superuser %}
            <li><a href="/account/">Manage Account</a></li>
        {% else %}
            <li><a href="/account/my/">My Account</a></li>
        {% endif %}
        <li><a href="/help">Help</a></li>
        <li><a href="/logout">Logout</a></li>
    </ul>
    </div>
{% endblock %}
{% block menu %}
    <div id="menu">

    </div>
{% endblock %}

templates/edit_user.html
{% extends "base_auth.html" %}

{% block content %}
    <div id="fileContainer">
                <div class="accArea">
                    <div id="accLabel">
                        <h2>My Account</h2>
                    </div>
                    <form action="/account/change/" method="post">
                        {%  csrf_token %}
                    <div class="error">{{ form.non_field_errors }}<br />
                        {{ error }}
                    {{ form.username.errors }}<br />
                    {{ form.old_password.errors }}<br />
                    {{ form.password.errors }}<br />
                    {{ form.password2.errors }}<br />
                    {{ form.email.errors }}<br />
                    </div>
                    <div class="dTable">
                        <div class="dRow">
                            <div class="dCell">Username</div>
                            <div class="dCell">
                                {{ form.id }}{{ form.username }}</div>
                        </div>
                        <div class="dRow">
                            <div class="dCell">Old Password</div>
                            <div class="dCell">
                                {{ form.old_password }}</div>
                        </div>
                        <div class="dRow">
                            <div class="dCell">New Password</div>
                            <div class="dCell">
                                {{ form.password }}</div>
                        </div>
                        <div class="dRow">
                            <div class="dCell">Confirm New Password</div>
                            <div class="dCell">
                                {{ form.password2 }}</div>
                        </div>
                        <div class="dRow">
                            <div class="dCell">Email</div>
                            <div class="dCell">
                                {{ form.email }}</div>
                        </div>
                        <div class="dRow">
                            <div class="dCell"></div>
                            <div class="dCell">
                                <input type="submit" value="Update"></div>
                        </div>
                    </div>
                    </form>
                </div>


            </div>
{% endblock %}
{% block popup %}
    <div class="popUpBack overlay hide">
        </div>

        <div class="popUp dialogBox hide">
            <div class="puTitle"><span class="puTitleText">Alert</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="message">MMMMMMM MMMMMMMMMMM
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="Cancel">Cancel</button><button class="puSave" value="OK">OK</button></div>
        </div>
        <div class="popUp alertBox hide">
            <div class="puTitle"><span class="puTitleText">Alert</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="message">MMMMMMM MMMMMMMMMMM
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="Cancel">OK</button></div>
        </div>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

<div id="outerLogin">
    <div id="titleBox"><h3>Login</h3></div>
    <div id="loginbox">
        <form action="/login/" method="post">
        <div class="error">{{ error }}</div>
        {% csrf_token %}
        <div class="label"><label>Username</label>{{ form.username }}</div>
        <div class="label"><label>Password</label>{{ form.password }}</div>
        <div class="link"><span class="forgot fLink">forgot password</span>&nbsp;{% if not has_user %}|&nbsp;<a href="/account/register/">register</a>{% endif %}</div>
        <input type="hidden" name="next" value="{{ next }}">
        <div class="submitlogin"><input type="submit" value="Login"></div>
        </form>
    </div>
</div>
{% endblock %}
{% block popup %}
    <div class="popUpBack overlay hide">
        </div>
            <div class="popUp emailForgot hide">
            <div class="puTitle">
                <span class="puTitleText">Forgot Password</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div class="dTable">
                    <div class="dRow">
                        <div class="dCell">Email</div>
                        <div class="dCell"><input type="text" id="emailForgotInput"></div>
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="cancel">Cancel</button><button class="puSave" value="execute">Reset Password</button></div>
        </div>
            <div class="popUp dialogBox hide">
            <div class="puTitle"><span class="puTitleText">Alert</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="message">MMMMMMM MMMMMMMMMMM
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="Cancel">Cancel</button><button class="puSave" value="OK">OK</button></div>
        </div>
        <div class="popUp alertBox hide">
            <div class="puTitle"><span class="puTitleText">Alert</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="message">MMMMMMM MMMMMMMMMMM
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="Cancel">OK</button></div>
        </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}


{% block content %}
    <div id="outerLogin">
        <div id="titleBox"><h3>Cyanobacterial Predictive Modeling - Administrative Website</h3></div>
        <div id="loginbox">
            <div id="regTitle"><h3>Create New Account</h3></div>
            <form action="/account/register/" method="post">
                {% csrf_token %}
            <div class="error">{{ form.non_field_errors }}</div>
            <div class="error">{{ form.username.errors }}</div>
            <div class="label"><label>Username</label>{{ form.username }}</div>
            <div class="error">{{ form.password.errors }}</div>
            <div class="label"><label>Password</label>{{ form.password }}</div>
            <div class="label"><label>Confirm Password</label>{{ form.password2 }}</div>
            <div class="error">{{ form.email.errors }}</div>
            <div class="label"><label>Email Address</label>{{ form.email }}</div>
            <div class="submitlogin"><input type="submit" value="Create an account" onclick="this.disabled=true,this.form.submit();"></div>
            </form>
        </div>
    </div>
{% endblock %}

templates/search_help_results.html
{% extends "base_auth.html" %}


{% block content %}

    <div id="fileContainer">
        <div id="fcLabal"><h3>Help</h3></div>
        <div id="mainFileContainer">
            <div id="helpArea">
                <div id="helpHeader">
                    <div id="helpHeaderLeft">
                        Search Result
                    </div>
                    <div id="helpHeaderRight">
                        <form action="/search_help/" method="get">
                        <input type="text" name="q" value="{{ query_string }}"><input type="submit" value="search...">

                            </form>
                    </div>
                </div>
                <div id="helpBody">
                    <div id="searchResult">
                        <ul>
                            {% for entry in entries %}
                                <li>
                                    <div><a href="/help/{{ entry.id }}/"> {{ entry.title }}</a></div>
                                    <div>{{ entry.content|slice:"10:100" }}....</div>

                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block popup %}
    <div class="popUpBack overlay hide">
        </div>
            <div class="popUp notification hide">
            <div class="puTitle"><span class="puTitleText">Notification</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="error"></div>
                    <div>
                        Title
                    </div>
                    <div class="sendNote"><input type="text" maxlength="100"></div>
                    <div>
                        Content
                    </div>
                    <div class="sendNote">
                            <textarea maxlength="2000"></textarea>
                    </div>

                </div>
            </div>
            <div class="puControl"><button class="puSave" value="Send">Send</button></div>
        </div>
        <div class="popUp dialogBox hide">
            <div class="puTitle"><span class="puTitleText">Alert</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="message">MMMMMMM MMMMMMMMMMM
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="Cancel">Cancel</button><button class="puSave" value="OK">OK</button></div>
        </div>
        <div class="popUp alertBox hide">
            <div class="puTitle"><span class="puTitleText">Alert</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="message">MMMMMMM MMMMMMMMMMM
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="Cancel">OK</button></div>
        </div>
            <div class="popUp ep hide">
            <div class="puTitle">
                <span class="puTitleText">Execute</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div class="dTable">
                    <div class="dRow">
                        <div class="dCell">Prediction Point</div>
                        <div class="dCell">
                            <span class="epText">{{ ep.prediction_point }} Day</span>
                            <span class="epInput hide"><input type="text" name="prediction_point" value="{{ ep.prediction_point }}" maxlength="30">Day<br />
                                <em>please input the days separated by comma (e.g 2, 5, 25, 40)</em>
                            </span>
                        </div>
                        <div class="dCell">
                            <div class="epEdit"><button value="Edit">Edit</button></div>
                            <div class="epSave hide"><button class="epSaveBtn" value="Save">Save</button><button class="epCancel" value="Edit">Cancel</button></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="cancel">Cancel</button><button class="puSave" value="execute">Execute Now</button></div>
        </div>
{% endblock %}

templates/view_help.html
{% extends "base_auth.html" %}



{% block content %}

    <div id="fileContainer">
        <div id="fcLabal"><h3>Help</h3></div>
        <div id="mainFileContainer">
            <div id="helpArea">
                <div id="helpHeader">
                    <div id="helpHeaderLeft">
                        Help Topic
                    </div>
                    <div id="helpHeaderRight">
                        <form action="/search_help/" method="get">
                        <input type="text" name="q" ><input type="submit" value="search...">

                            </form>
                    </div>
                </div>
                <div id="helpBody">
                    <div id="helpMenu">
                        <ul class="ulUp">
                            {% for cat in categories %}
                            <li>
                                {{ cat.name }}
                                <ul class="ulDown">
                                    {% for h in cat.helptopic_set.all %}
                                    <li>
                                        <a href="/help/{{ h.id }}/">{{ h.title }}</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div id="helpContent">
                        <h4>{{ topic.title }}</h4>
                        {% autoescape off %}
                            {{ topic.content }}
                        {% endautoescape %}
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block popup %}
    <div class="popUpBack overlay hide">
        </div>
            <div class="popUp notification hide">
            <div class="puTitle"><span class="puTitleText">Notification</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="error"></div>
                    <div>
                        Title
                    </div>
                    <div class="sendNote"><input type="text" maxlength="100"></div>
                    <div>
                        Content
                    </div>
                    <div class="sendNote">
                            <textarea maxlength="2000"></textarea>
                    </div>

                </div>
            </div>
            <div class="puControl"><button class="puSave" value="Send">Send</button></div>
        </div>
        <div class="popUp dialogBox hide">
            <div class="puTitle"><span class="puTitleText">Alert</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="message">MMMMMMM MMMMMMMMMMM
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="Cancel">Cancel</button><button class="puSave" value="OK">OK</button></div>
        </div>
        <div class="popUp alertBox hide">
            <div class="puTitle"><span class="puTitleText">Alert</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div>
                    <div class="message">MMMMMMM MMMMMMMMMMM
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="Cancel">OK</button></div>
        </div>
            <div class="popUp ep hide">
            <div class="puTitle">
                <span class="puTitleText">Execute</span>
                <span class="puClose">X</span>
            </div>
            <div class="puBody">
                <div class="dTable">
                    <div class="dRow">
                        <div class="dCell">Prediction Point</div>
                        <div class="dCell">
                            <span class="epText">{{ ep.prediction_point }} Day</span>
                            <span class="epInput hide"><input type="text" name="prediction_point" value="{{ ep.prediction_point }}" maxlength="30">Day<br />
                                <em>please input the days separated by comma (e.g 2, 5, 25, 40)</em>
                            </span>
                        </div>
                        <div class="dCell">
                            <div class="epEdit"><button value="Edit">Edit</button></div>
                            <div class="epSave hide"><button class="epSaveBtn" value="Save">Save</button><button class="epCancel" value="Edit">Cancel</button></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="puControl"><button class="puCancel" value="cancel">Cancel</button><button class="puSave" value="execute">Execute Now</button></div>
        </div>
{% endblock %}